#-------------------------------
# General Site Settings

menu:
- {name: 'Home',     url: ''}
- {name: 'Posts',    url: 'posts'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Music',  folder: 'music', file:'projects/music.md'} 
- {name: 'Design',  url: 'design'}
- {name: 'Art',  url: 'art'}
- {name: 'Project Four',  url: 'proj-4'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/TazSolace'}
- {icon: 'youtube',   link: 'https://www.youtube.com/@TazSolace'}
- {icon: 'envelope',  link: 'https://linktr.ee/tazsolace'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Taz Solace - Multidisciplinary Creative Queer Non-Binary Singer-Songwriter, Artist, Designer'
  rel-author: 'Taz Solace'
  rel-publisher: 'Taz Solace'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
